name: backend

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
    python:
        runs-on: ubuntu-latest
        environment: env
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Python environment
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"

        - name: Update Pip
          run: python -m pip install --upgrade pip

        - name: Run Black
          uses: psf/black@stable
          with:
            options: --check --verbose --exclude "migrations/"
            src: ./backend
        - name: Run ruff
          working-directory: ./backend
          run: python ruff .

        - name: Run mypy
          working-directory: ./backend
          run: python mypy .


