name: backend

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
    prettier:
      name: Run PR Frontend Formatting Check
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Run Prettier
          uses: creyD/prettier_action@v4.3 
          with:
            working_directory: ./frontend
            dry: True
            prettier_options: --check