name: Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  django:
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USER: ${{ secrets.DATABASE_USER}}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD}}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST}}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT}}
      DEBUG: ${{vars.DEBUG}}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SQLLITE: ${{ vars.SQLLITE}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        working-directory: ./backend
        run: |
          python manage.py migrate
          python manage.py test

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: --check --verbose --exclude "migrations/"
          src: ./backend
